# Generated by Django 4.0.4 on 2022-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
